Add FAQ tab content
RedHatInsights/trust-frontend pull request #9
Opened 2020-09-09 11:31 UTC by mhuth

Having problems pulling the content dynamically from https://access.redhat.com/hydra/rest/drupal/articles/4602981 so hardcoding it for the time being until I sort it out (or give up and run away).

2020-09-09 11:33 UTC, mhuth commented
![Screenshot from 2020-09-09 21-32-50](https://user-images.githubusercontent.com/4008744/92593215-1363e300-f2e4-11ea-96d7-0b844d93a523.png)

2020-09-09 11:39 UTC, AllenBW requested changes
just a few things! but m real excited forrrrrrr this... makes it look sao official :godmode:

2020-09-09 11:39 UTC, AllenBW commented on package.json
> +    "react-markdown": "^4.3.1",
gottal lock this version down 😬 🤗

2020-09-09 11:39 UTC, AllenBW commented on src/Components/Tabs/FAQ.js
> +    useEffect(() => {
lets comment out the block if it doesn't work yet, no sense in pounding n api for no reason 💯

2020-09-09 11:39 UTC, AllenBW commented on src/Components/Tabs/FAQ.scss
> +ul {
needs ah space aboveeee

2020-09-09 11:39 UTC, AllenBW commented on src/Components/Tabs/FAQ.scss
> +.ins-c-card {
i think this is n existing pf class name, might want to rename to something else, more specific to the app

BUT we should probably use things that are similar to whats in cardcollection.scss, maybe bubble that styling up to app.scss, make it common across?

2020-09-09 11:39 UTC, AllenBW commented on src/Messages.js
> +        defaultMessage: '<p><strong>Q: What is Red Hat Insights?</strong><br /> <strong>A</strong>: Red Hat® Insights provides proactive analytics with remediation guidance for Red Hat Enterprise Lin
lawl, what ah long line HAHAHA HAVE FUN TRANSLATING THAT ONE 🌞

2020-09-10 11:28 UTC, AllenBW approved these changes
delicious! yeah m down with this 🙇 🤗 👍 nicely done @mhuth

2020-09-10 11:28 UTC, merged